pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash

  - name: merge when all requested reviews are valid
    conditions:
      - status-success=Travis CI - Branch
      - status-success=Travis CI - Pull Request
      - status-success=SonarCloud Code Analysis
      - status-success=Codacy/PR Quality Review
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - base!=master
    actions:
        merge:
          method: squash

  - name: Merge x -> master | Cleanup afterwards
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
      delete_head_branch: {}
